config/routes.rb
Rails.application.routes.draw do

  namespace :sponsors do
    resources :franchises
  end

  match 'myportal' => 'myportal#index', :via => :get, as: :myportal
  match 'myportal/details' => 'myportal/details#show', :via => :get, as: :myportal_details_show
  match 'myportal/advertisements' => 'myportal/advertisements#index', :via => :get, as: :myportal_advertisements
  match 'myportal/visitors' => 'myportal/visitors#index', :via => :get, as: :myportal_visitors

  namespace :sponsorships do
    resources :vendors
  end

  namespace :advertisements do
    resources :groups
    resources :templates
  end

  devise_for :users, :controllers => { :registrations_users => 'registrations_users'}

  devise_for :sponsors, controllers: {registrations: 'sponsors/registrations', sessions: 'sponsors/sessions'}

  namespace :sponsors do
    resources :levels
    resources :portals
    resources :details
    resources :types
    resources :styles
  end

   namespace :advertisements do
     resources :advertisements

   end

  get 'welcome' => 'welcome#index', as: 'welcome'

  match 'myportal' => 'sponsors/portals#myportal', :via => :get, as: :sponsors_portals_myportal

  root 'welcome#index'

end

app/models/sponsors.rb
module Sponsors
  def self.table_name_prefix
    'sponsors_'
  end
end

app/models/sponsors/level.rb
class Sponsors::Level < ActiveRecord::Base

  has_many :sponsors
end

app/controllers/-sponsors_controller.rb
class SponsorsController < ApplicationController
  respond_to :html

  before_action :set_sponsor, only: [:edit, :update, :destroy]
  before_action :set_portal, only: :show
  before_action :set_sponsor_type, only: :show
  before_action :set_clients, only: :show

  # before_action :update_sponsored_count, only:  :show
  after_action :update_sponsored_count, only: [:create, :destroy]

  def index
    sponsors = Sponsor.all
    @sponsors = sponsors.collect { |sponsor| SponsorDecorator.new(sponsor,view_context) }
    respond_with(@sponsors)
  end

  def show
    sponsor = Sponsor.find(params[:id])
    @sponsor = SponsorDecorator.new(sponsor, view_context)
    respond_with(@sponsor)

  end

  def new
    @sponsor = Sponsor.new
    # @sponsor.users.new
    respond_with(@sponsor)
  end

  def edit
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)
    @sponsor.save
    respond_with(@sponsor)
  end

  def update
    @sponsor.update(sponsor_params)
    respond_with(@sponsor)
  end

  def destroy
    @sponsor.destroy
    respond_with(@sponsor)
  end

  private
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    def set_portal
      sponsor = Sponsor.find(params[:id])
      @sponsor = SponsorDecorator.new(sponsor, view_context)
    end

    #Used to determine which ad is served
    def set_sponsor_type
      puts "Entering set_sponsor_type"
      @sponsored = @sponsor.sponsor_type.symbol_name.to_sym
      puts "set_sponsor_type: #{@sponsored}"
    end

    #Set clients based upon user type
    def set_clients

      if @sponsored  == :reagent
        @prospects = Csponsorship.where(sponsor_id: @sponsor.id)
      else
        @prospects = Bsponsorship.where(sponsor_id: @sponsor.id)
      end
    end

    #Update count for display
    def update_sponsored_count
      if @sponsored  == :reagent

        count = Csponsorship.where(sponsor_id: @sponsor.id).count
        @sponsor = Sponsor.find(params[:id])
        @sponsor.sponsored = count
        @sponsor.save!

      else
        puts "inside update sponsors"
        count = Bsponsorship.where(sponsor_id: @sponsor.id).count
        @sponsor = Sponsor.find(params[:id])
        puts "sponsor: #{@sponsor.inspect}"
        @sponsor.sponsored = count
        @sponsor.save!

      end
    end

    def sponsor_params
      params.require(:sponsor).permit(:industry_id, :user_id, :sponsor_type_id, :business_name, :phone, :address_1, :address_2, :city, :state_id, :zipcode, :website, :notes)
    end
end

app/controllers/api/v1/sponsors_controller.rb
module Api
  module V1
    class SponsorsController < ApplicationController

      respond_to :json

      skip_before_filter :verify_authenticity_token

      def index
        render json: Sponsor.all
      end

      def show
        render json: sponsor
      end
      #
      # def new
      #
      # end

      def create

        sponsor = Sponsor.new(sponsor_params)

        if sponsor.save
          render json: sponsor
        else
          render json: sponsor.errors, status: 422
        end

        # render json: Sponsor.create(sponsor_params)
      end

      def update
        render json: sponsor.update(sponsor_params)
      end

      def destroy
        render json: sponsor.destroy
      end

      private

      def sponsor
         Sponsor.find(params[:id])
         # mouser = '99502e37-001e-419b-a3ec-b32121e598c7'
         # Sponsor.find(mouser)
      end

      def sponsor_params
        params.require(:sponsor).permit(:user_name, :business_name, :first_name, :last_name, :primary_phone, :email, :campaign_id, :password, :password_confirmation)
      end

    end

  end #end v1
end # end api

app/controllers/myportal/details_controller.rb
class  Myportal::DetailsController < Sponsors::DetailsController

  # Restrict this to sponsors only

  layout "sponsor"
s
  respond_to :html

  before_action :set_sponsors_detail, only: [:show, :edit, :update, :destroy]

  # before_action :set_sponsor, only: :show
  #before_action :verify_sponsor_detail_record_exists, only: :show

  def index
    # Only display for staff
    unless current_sponsor.nil?
      redirect_to '/myportal'
    else
    sponsors_details = Sponsors::Detail.all
    @sponsors_details = sponsors_details.collect { |sponsors_detail| Sponsors::DetailDecorator.new(sponsors_detail,view_context) }
    respond_with(@sponsors_details)
    end
  end

  def show
          @sponsors_detail = Sponsors::DetailDecorator.new(@sponsors_detail, view_context)
      respond_with(@sponsors_detail)
    # end
  end

  def new
    puts 'sponsors_details#new'
    @sponsors_detail = SponsorsDetail.new
    respond_with(@sponsors_detail)
  end

  def edit
  end

  def create
    @sponsors_detail = Sponsors::Detail.new(sponsors_detail_params)
    @sponsors_detail.sponsor_id = SponsorService::GetSponsoreeRecord.call(current_user).id
    # @sponsor.sponsor_id = Sponsor.where(user_id: current_user_id).first.id
    @sponsor_detail.save
    respond_with(@sponsors_detail)
  end

  def update
    @sponsors_detail.update(sponsors_detail_params)
    respond_with(@sponsors_detail)
  end

  def destroy
    @sponsors_detail.destroy
    respond_with(@sponsors_detail)
  end

  private

    #
    # def set_sponsor
    #   # @sponsor = Sponsor.where(user_id: current_user.id).first
    #   @sponsors_
    #   puts "set_sponsor #{@sponsor}"
    # end
    #
    # def verify_sponsor_detail_record_exists
    #   #If no record is found the redirect to new
    #   # Look for the record that belongs to this person
    #   @sponsors_detail = Sponsors::Detail.where(sponsor_id: @sponsor.id).first
    #   puts "@sponsor_detail: #{@sponsors_detail.inspect}"
    #   if @sponsers_detail == nil?
    #     redirect_to new_sponsors_detail
    #   end
    # end

    def set_sponsors_detail
      # @sponsors_detail = Sponsors::Detail.find(params[:id])
      sponsor_id = current_sponsor.id
      # Get the current user's sponsor record unless staff
      @sponsors_detail = Sponsors::Detail.where(sponsor_id: sponsor_id).first
    end

    def sponsors_detail_params
      params.require(:sponsors_detail).permit(:sponsor_id, :company_name, :contact_last_name, :contact_first_name, :phone_1, :phone_2, :website, :email, :tag_line_1, :tag_line_2, :welcome_greeting, :return_greeting, :logo_file, :headshot_file, :sponsors_style_id)
    end
end

app/controllers/sponsors/classes_controller.rb
class Sponsors::ClassesController < ApplicationController
  before_action :set_sponsors_class, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    sponsors_classes = Sponsors::Class.all
    @sponsors_classes = sponsors_classes.collect { |sponsors_class| Sponsors::ClassDecorator.new(sponsors_class, view_context) }
    # @sponsors_classes = Sponsors::Class.all
    respond_with(@sponsors_classes)
  end

  def show
    @sponsors_class = Sponsors::ClassDecorator.new(@sponsors_class, view_context)
     respond_with(@sponsors_class)
  end

  def new
    @sponsors_class = Sponsors::Class.new
    respond_with(@sponsors_class)
  end

  def edit
  end

  def create
    @sponsors_class = Sponsors::Class.new(sponsors_class_params)
    @sponsors_class.save
    respond_with(@sponsors_class)
  end

  def update
    @sponsors_class.update(sponsors_class_params)
    respond_with(@sponsors_class)
  end

  def destroy
    @sponsors_class.destroy
    respond_with(@sponsors_class)
  end

  private
    def set_sponsors_class
      @sponsors_class = Sponsors::Class.find(params[:id])
    end

    def sponsors_class_params
      params.require(:sponsors_class).permit(:name, :description, :archived)
    end
end

app/controllers/sponsors/details_controller.rb
class Sponsors::DetailsController < ApplicationController

  # Restrict this to sponsors only

  respond_to :html
   before_action :set_sponsors_detail, only: [:show, :edit, :update, :destroy]
  layout "sponsor"

  respond_to :html

  before_action :set_sponsors_detail, only: [:show, :edit, :update, :destroy]


  # before_action :set_sponsor, only: :show
  #before_action :verify_sponsor_detail_record_exists, only: :show

  def index

    sponsors_details = Sponsors::Detail.all
    @sponsors_details = sponsors_details.collect { |sponsors_detail| Sponsors::DetailDecorator.new(sponsors_detail,view_context) }
    respond_with(@sponsors_details)
  end

  def show
    # Get the current user's sponsor record
    # sponsor_id = Sponsor.where(user_id: current_user.id).first

    # Get the sponsoree record
    # sponsoree = SponsorService::GetSponsoreeRecord.call(current_user)
    # puts ''
    # sponsors_detail = Sponsors::Detail.where(sponsor_id: params[:id]).first
    # puts "sponsor_detail: #{sponsors_detail.inspect}"
    # puts ''
    # Has this sponsor completed their ad details?
    # if sponsor_detail.nil?
    #   puts 'render new'
    #   redirect_to :new_sponsor_detail
    # else
    # @sponsors_type = Sponsors::TypeDecorator.new(@sponsors_type, view_context)
    # respond_with(@sponsors_type)

      @sponsors_detail = Sponsors::DetailDecorator.new(@sponsors_detail, view_context)

    # Only display for staff
    unless current_sponsor.nil?
      redirect_to '/myportal'
    else
    sponsors_details = Sponsors::Detail.all
    @sponsors_details = sponsors_details.collect { |sponsors_detail| Sponsors::DetailDecorator.new(sponsors_detail,view_context) }
    respond_with(@sponsors_details)
    end
  end

  def show
          @sponsors_detail = Sponsors::DetailDecorator.new(@sponsors_detail, view_context)

      respond_with(@sponsors_detail)
    # end
  end

  def new
    puts 'sponsors_details#new'
    @sponsors_detail = SponsorsDetail.new
    respond_with(@sponsors_detail)
  end

  def edit
  end

  def create
    @sponsors_detail = Sponsors::Detail.new(sponsors_detail_params)
    @sponsors_detail.sponsor_id = SponsorService::GetSponsoreeRecord.call(current_user).id
    # @sponsor.sponsor_id = Sponsor.where(user_id: current_user_id).first.id
    @sponsor_detail.save
    respond_with(@sponsors_detail)
  end

  def update
    @sponsors_detail.update(sponsors_detail_params)
    respond_with(@sponsors_detail)
  end

  def destroy
    @sponsors_detail.destroy
    respond_with(@sponsors_detail)
  end

  private

    #
    # def set_sponsor
    #   # @sponsor = Sponsor.where(user_id: current_user.id).first
    #   @sponsors_
    #   puts "set_sponsor #{@sponsor}"
    # end
    #
    # def verify_sponsor_detail_record_exists
    #   #If no record is found the redirect to new
    #   # Look for the record that belongs to this person
    #   @sponsors_detail = Sponsors::Detail.where(sponsor_id: @sponsor.id).first
    #   puts "@sponsor_detail: #{@sponsors_detail.inspect}"
    #   if @sponsers_detail == nil?
    #     redirect_to new_sponsors_detail
    #   end
    # end

    def set_sponsors_detail

      @sponsors_detail = Sponsors::Detail.find(params[:id])

      # @sponsors_detail = Sponsors::Detail.find(params[:id])
      sponsor_id = current_sponsor.id
      # Get the current user's sponsor record unless staff
      @sponsors_detail = Sponsors::Detail.where(sponsor_id: sponsor_id).first

    end

    def sponsors_detail_params
      params.require(:sponsors_detail).permit(:sponsor_id, :company_name, :contact_last_name, :contact_first_name, :phone_1, :phone_2, :website, :email, :tag_line_1, :tag_line_2, :welcome_greeting, :return_greeting, :logo_file, :headshot_file, :sponsors_style_id)
    end
end

app/controllers/sponsors/franchises_controller.rb
class Sponsors::FranchisesController < ApplicationController
  before_action :set_sponsors_franchise, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    sponsors_franchises = Sponsors::Franchise.all
    @sponsors_franchises = sponsors_franchises.collect { |sponsors_franchise| Sponsors::FranchiseDecorator.new(sponsors_franchise,view_context) }
    respond_with(@sponsors_franchises)
  end

  def show
    @sponsors_franchise = Sponsors::FranchiseDecorator.new(@sponsors_franchise, view_context)
    respond_with(@sponsors_franchise)
  end

  def new
    @sponsors_franchise = Sponsors::Franchise.new
    respond_with(@sponsors_franchise)
  end

  def edit
  end

  def create
    @sponsors_franchise = Sponsors::Franchise.new(sponsors_franchise_params)
    @sponsors_franchise.save
    respond_with(@sponsors_franchise)
  end

  def update
    @sponsors_franchise.update(sponsors_franchise_params)
    respond_with(@sponsors_franchise)
  end

  def destroy
    @sponsors_franchise.destroy
    respond_with(@sponsors_franchise)
  end

  private
    def set_sponsors_franchise
      @sponsors_franchise = Sponsors::Franchise.find(params[:id])
    end

    def sponsors_franchise_params
      params.require(:sponsors_franchise).permit(:title, :description, :archived)
    end
end

app/controllers/sponsors/invitations_controller.rb
class Sponsors::InvitationsController < ApplicationController

   rescue_from ActiveRecord::RecordNotFound, with: :campaign_not_found
   rescue_from PG::InvalidTextRepresentation, with: :invalid_campaign_id

  #  before_action ->(campaign_id=params[:id]) {verify_campaign_exists campaign_id}, only:%w{invitation}

  def index
    render 'unfortunately'
  end

  def invitation
    # get the campaign_id from parameters
    campaign_id = params[:campaign_id]

    puts "campaign_id #{campaign_id}"

    if campaign_id
      puts "Entered if campaign_id"
      @campaign_record = CampaignService::GetCampaignRecordById.call(campaign_id)
      # rescue ActiveRecord::RecordNotFound
      #   redirect_to :controller => "sponsors_invitations", :action => "index"
      #   return
      # end
      # Get sponsor status
      sponsor_id = @campaign_record.sponsor_id
      sponsor = Sponsor.find(sponsor_id)
      puts "Sponsors::Invitations sponsor : #{sponsor.inspect}"

      # pass sponsor and advertisment_i

      @ad_html = AdvertisementService::AdComposer.call(sponsor, @campaign_record)
      puts "@ads_html #{@ad_html}"
      # @ad_html = '<div><b>Ad Goes Here</b></div>'
      # Ad to be shown
      #  @campaign_record.advertisements_advertisement_id

      # Returns hash with active, suspended, grace_ends and grace_remaining
      # [active: {true,false}, suspended: {true, false}, grace_ends: date, grace_remaining: {0-x in days}]
      # @sponsor_account_status = AccountingService::GetAccountStatusBySponsorId.call(sponsor_id)

      # Save the campaign_id to a cookie for use in registration
      puts 'Saving Sponsors cookie'
      cookies.permanent.signed['campaign'] = campaign_id

        # render 'sponsors/welcome/new'

    else
      render 'unfortunately'
    end
  end

  def show

  end

  def unfortunately

  end

private
  #Has a valid campaign been submitted
  def verify_campaign_exists campaign_id

    marketing_campaign = Marketing::Campaign.find(campaign_id)

    # Send the user away if the campaign doesn't exist
    # otherwise continue
    render '/welcome' unless marketing_campaign

  end


  def campaign_not_found
    redirect_to sponsors_invitations_unfortunately_path, :notice => 'Campaign record not found'
  end

  def invalid_campaign_id
    puts 'Bad UUID in campaign'
    redirect_to sponsors_invitations_unfortunately_path, :notice => 'Campaign record not found'
  end

end

app/controllers/sponsors/levels_controller.rb
class Sponsors::LevelsController < ApplicationController
  before_action :set_sponsors_level, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    sponsors_levels = Sponsors::Level.all
    @sponsors_levels = sponsors_levels.collect { |sponsors_level| Sponsors::LevelDecorator.new(sponsors_level, view_context) }
    respond_with(@sponsors_levels)
  end

  def show
    @sponsors_level = Sponsors::LevelDecorator.new(@sponsors_level, view_context)
    respond_with(@sponsors_level)
  end

  def new
    @sponsors_level = Sponsors::Level.new
    respond_with(@sponsors_level)
  end

  def edit
  end

  def create
    @sponsors_level = Sponsors::Level.new(sponsors_level_params)
    @sponsors_level.save
    respond_with(@sponsors_level)
  end

  def update
    @sponsors_level.update(sponsors_level_params)
    respond_with(@sponsors_level)
  end

  def destroy
    @sponsors_level.destroy
    respond_with(@sponsors_level)
  end

  private
    def set_sponsors_level
      @sponsors_level = Sponsors::Level.find(params[:id])
    end

    def sponsors_level_params
      params.require(:sponsors_level).permit(:title, :description, :archived)
    end
end

app/views/sponsors/details/_form.html.haml
.row
  .small-12.columns
    = simple_form_for(@sponsors_detail) do |f|
      = f.error_notification

      .form-inputs
        -#= f.input :sponsor_id
        = f.input :company_name
        = f.input :contact_last_name
        = f.input :contact_first_name
        = f.input :phone_1
        = f.input :phone_2
        = f.input :website
        = f.input :email
        = f.input :tag_line_1
        = f.input :tag_line_2
        = f.input :welcome_greeting
        = f.input :return_greeting
        = f.input :logo_filename
        = f.input :headshot_filename
        = f.collection_select :sponsors_style_id, Sponsors::Style.all, :id, :title

      .form-actions
        = f.button :submit

app/views/sponsors/details/edit.html.haml
.row
  .small-6.columns
    %h4= t('views.sponsors_details.edit.title')

    = render 'form'

    = link_to t('views.nav.cancel'), @sponsors_detail
    -# \|
    -# = link_to t('views.nav.cancel'), sponsors_details_path
    = link_to t('views.nav.cancel'), @sponsors_detail
    -# \|
    -# = link_to t('views.nav.cancel'), sponsors_details_path

app/views/sponsors/details/index.html.haml
%h1 Listing sponsor_details

%table
  %tr
    %th Sponsor
    %th Company name
    %th Contact last name
    %th Contact first name
    -# %th Phone 1
    -# %th Phone 2
    -# %th Website
    -# %th Email
    -# %th Tag line 1
    -# %th Tag line 2
    -# %th Welcome greeting
    -# %th Return greeting
    -# %th Logo filename
    -# %th Headshot filename
    %th
    %th
    %th

  - @sponsors_details.each do |sponsors_detail|
    %tr

      %td= sponsors_detail.d_sponsors_name
      %td= sponsors_detail.d_sponsor_business_name

      %td= sponsors_detail.company_name
      %td= sponsors_detail.contact_last_name
      %td= sponsors_detail.contact_first_name
      -# %td= sponsors_detail.phone_1
      -# %td= sponsors_detail.phone_2
      -# %td= sponsors_detail.website
      -# %td= sponsors_detail.email
      -# %td= sponsors_detail.tag_line_1
      -# %td= sponsors_detail.tag_line_2
      -# %td= sponsors_detail.welcome_greeting
      -# %td= sponsors_detail.return_greeting
      -# %td= sponsors_detail.logo_filename
      -# %td= sponsors_detail.headshot_filename
      %td= link_to 'Show', sponsors_detail
      %td= link_to 'Edit', edit_sponsors_detail_path(sponsors_detail)
      %td= link_to 'Destroy', sponsors_detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sponsor detail', new_sponsors_detail_path

app/views/sponsors/details/new.html.haml
.row
  .small-6.columns
    %h4 Please enter your marketing details.
    %p This information will be used when generating your ads.

    = render 'form'

    = link_to 'Back', sponsor_details_path

app/views/sponsors/details/show.html.haml
.row
  .small-8.columns
    %p#notice= notice
    %h4= t('views.sponsors_details.show.title')
    %table.table-settings

      %tr
        %td.small-4
          %b= t('activerecord.attributes.shared.company_name')
        %td
          = @sponsors_detail.d_company_name
      %tr
        %td
          %b=  t('activerecord.attributes.shared.last_name')
        %td
          = @sponsors_detail.d_contact_last_name
      %tr
        %td
          %b=  t('activerecord.attributes.shared.first_name')
        %td
          = @sponsors_detail.d_contact_first_name
      %tr
        %td
          %b=  t('activerecord.attributes.shared.phone_1')
        %td
          = @sponsors_detail.d_phone_1
      %tr
        %td
          %b=  t('activerecord.attributes.shared.phone_2')
        %td
          = @sponsors_detail.d_phone_2
      %tr
        %td
          %b= t('activerecord.attributes.shared.website')
        %td
          = @sponsors_detail.d_website
      %tr
        %td
          %b= t('activerecord.attributes.shared.email')
        %td
          = @sponsors_detail.d_email
      %tr
        %td
          %b= t('activerecord.attributes.shared.tag_line_1')
        %td
          =@sponsors_detail.d_tag_line_1
      %tr
        %td
          %b= t('activerecord.attributes.shared.tag_line_2')
        %td
          = @sponsors_detail.d_tag_line_2
      %tr
        %td
          %b= t('activerecord.attributes.shared.welcome_greeting')
        %td
          = @sponsors_detail.d_welcome_greeting
      %tr
        %td
          %b= t('activerecord.attributes.shared.return_greeting')
        %td
          = @sponsors_detail.d_return_greeting
      %tr
        %td
          %b= t('activerecord.attributes.shared.logo_filename')
        %td
          = @sponsors_detail.d_logo_filename
      %tr
        %td
          %b= t('activerecord.attributes.shared.headshot_filename')
        %td
          = @sponsors_detail.d_headshot_filename
      %tr
        %td
          %b= t('activerecord.attributes.shared.style_title')
        %td
          = @sponsors_detail.d_style_title

    -# = link_to t('views.nav.edit'), edit_sponsors_detail_path(@sponsors_detail), { id: 'link_show_edit'}
    -#\|
    = link_to t('views.nav.back'), sponsors_details_path, { class: 'link_show_back'}

    = link_to t('views.nav.edit'), edit_sponsors_detail_path(@sponsors_detail), { id: 'link_show_edit'}
    -#\|
    -# = link_to t('views.nav.back'), sponsors_details_path, { class: 'link_show_back'}

.row
  .small-3.columns
    %p