config/routes.rb
Rails.application.routes.draw do

  namespace :sponsors do
    resources :franchises
  end

  match 'myportal' => 'myportal#index', :via => :get, as: :myportal
  match 'myportal/details' => 'myportal/details#show', :via => :get, as: :myportal_details_show
  match 'myportal/advertisements' => 'myportal/advertisements#index', :via => :get, as: :myportal_advertisements
  match 'myportal/visitors' => 'myportal/visitors#index', :via => :get, as: :myportal_visitors

  namespace :sponsorships do
    resources :vendors
  end

  namespace :advertisements do
    resources :groups
    resources :templates
  end

  devise_for :users, :controllers => { :registrations_users => 'registrations_users'}

  devise_for :sponsors, controllers: {registrations: 'sponsors/registrations', sessions: 'sponsors/sessions'}

  namespace :sponsors do
    resources :levels
    resources :portals
    resources :details
    resources :types
    resources :styles
  end

   namespace :advertisements do
     resources :advertisements

   end

  get 'welcome' => 'welcome#index', as: 'welcome'

  match 'myportal' => 'sponsors/portals#myportal', :via => :get, as: :sponsors_portals_myportal

  root 'welcome#index'

end

app/models/-sponsor.rb
class Sponsor < ActiveRecord::Base  belongs_to :lookups_state, :class_name => 'Lookups::State'  has_many :marketing_campaigns, :class_name => 'Marketing::Campaign'  # Include default devise modules. Others available are:  # :confirmable, :lockable, :timeoutable and :omniauthable  devise :database_authenticatable, :registerable,         :recoverable, :rememberable, :trackable, :validatable  # Used by devise for validations  validates_presence_of :user_name  validates_uniqueness_of :user_name  #For Devise to use user_name  def email_required?    false  endend

app/models/accounting.rb
module Accounting
  def self.table_name_prefix
    'accounting_'
  end
end

app/models/advertisements.rb
module Advertisements
  def self.table_name_prefix
    'advertisements_'
  end
end

app/models/images.rb
module Images
  def self.table_name_prefix
    'images_'
  end
end

app/models/lookups.rb
module Lookups
  def self.table_name_prefix
    'lookups_'
  end
end

app/models/marketing.rb
module Marketing
  def self.table_name_prefix
    'marketing_'
  end
end

app/models/new_sponsor.rb
# Used by the new sponsor form
class NewSponsor
  include ActiveModel::Model

  # Campaign methods
  attr_accessor :campaign_id

  # User methods
  attr_accessor :email, :last_name, :first_name, :password, :password_confirmation

  # Sponsor methods
  attr_accessor :business_name, :phone, :address_1, :address_2, :city, :state_id, :zipcode
  attr_accessor :website, :sponsor_email




end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  # Currently used model as of 01/06/15

  belongs_to :level
  belongs_to :sponsors_type, :class_name => 'Sponsors::Type'
  belongs_to :sponsors_level, :class_name => 'Sponsors::Level'
  belongs_to :lookups_state, :class_name => 'Lookups::State'

  has_one :sponsors_details, :class_name => 'Sponsors::Detail' #, foreign_key: "sponsor_id"

  has_many :advertisements_advertisements, :class_name => 'Advertisements::Advertisement'
  has_many :advertisements_templates, :class_name => 'Advertisements::Template'
  has_many :advertisements_rotations, :class_name => 'Advertisements::Rotation'
  has_many :marketing_campaigns, :class_name => 'Marketing::Campaign'
  has_many :marketing_channels, :class_name => 'Marketing::Channel'
  has_many :sponsorships_businesses, :class_name => 'Sponsorships::Businesses', foreign_key: "sponsor_id"
  has_many :sponsorships_businesses, :class_name => 'Sponsorships::Businesses', foreign_key: "vendor_id"

  # , :class_name => 'Sponsorships::Businesses'
  # has_many :sponsorships_businesses, :class_name => 'Sponsorships::Businesses', foreign_key: "sponsored"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  #  Added for ember devise
  before_save :ensure_authentication_token

  attr_accessor :new_sponsor_sign_up # Used to skip full validations on sign_up form
  # validates:
  validates :user_name, presence: true, length: { within: 6..20 }
  validates :email, presence:true
  validates :license_number, presence: true, unless: :new_sponsor_sign_up
  validates :license_email, presence: true, unless: :new_sponsor_sign_up
  validates :business_name, presence: true, unless: :new_sponsor_sign_up
  validates :first_name, presence: true, unless: :new_sponsor_sign_up
  validates :last_name, presence: true, unless: :new_sponsor_sign_up
  validates :primary_phone, presence: true, unless: :new_sponsor_sign_up
  validates :address_1, presence: true, unless: :new_sponsor_sign_up
  # validates :address_2
  validates :city, presence: true, unless: :new_sponsor_sign_up
  # lookups_state_id uuid,
  validates :zipcode, presence: true, unless: :new_sponsor_sign_up
  validates :website, presence: true, unless: :new_sponsor_sign_up


  # Create sort order / used in templates ctrl
  def order_by_business_name
    order(self.business_name)
  end

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end


  # Used in staff portal
  def self.latest_visitors(limit)
    where("last_sign_in_at IS NOT NULL").order('last_sign_in_at DESC').limit(limit)
  end



  #For Devise to use user_name
  def email_required?
    false
  end

  private
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Sponsor.where(authentication_token: token).first
    end
  end

end

app/models/sponsors.rb
module Sponsors
  def self.table_name_prefix
    'sponsors_'
  end
end

app/models/sponsorships.rb
module Sponsorships
  def self.table_name_prefix
    'sponsorships_'
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Used by devise for validations
  validates_presence_of :user_name
  validates_uniqueness_of :user_name



  #For Devise to use user_name
  def email_required?
    false
  end
end

app/models/statistics.rb
module Statistics
  def self.table_name_prefix
    'statistics_'
  end
end

app/models/test.rb
class Test < ActiveRecord::Base

  validates_presence_of :name
  validates_presence_of :color
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  belongs_to :campaign

  has_many :sponsors_sponsors, :class_name => 'Sponsors::Sponsor'


  # Works with Devise in signup form
  # accepts_nested_attributes_for :sponsors

  # Scopes
  def self.consumers
    where(role: 'user')
  end

  def user_full_name
    "#{last_name}, #{first_name}"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/myportal_helper.rb
module MyportalHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/*sponsor_details/_form.html.haml
.row
  .small-12.columns
    = simple_form_for(@sponsor_detail) do |f|
      = f.error_notification

      .form-inputs
        -#= f.input :sponsor_id
        = f.input :company_name
        = f.input :contact_last_name
        = f.input :contact_first_name
        = f.input :phone_1
        = f.input :phone_2
        = f.input :website
        = f.input :email
        = f.input :tag_line_1
        = f.input :tag_line_2
        = f.input :welcome_greeting
        = f.input :return_greeting
        = f.input :logo_filename
        = f.input :headshot_filename

      .form-actions
        = f.button :submit

app/views/*sponsor_details/edit.html.haml
.row
  .small-6.columns
    %h4= t('views.sponsor_details.edit.title')

    = render 'form'

    = link_to t('views.nav.show'), @sponsor_detail
    \|
    = link_to t('views.nav.back'), sponsor_details_path

app/views/*sponsor_details/index.html.haml
%h1 Listing sponsor_details

%table
  %tr
    %th Sponsor
    %th Company name
    %th Contact last name
    %th Contact first name
    %th Phone 1
    %th Phone 2
    %th Website
    %th Email
    %th Tag line 1
    %th Tag line 2
    %th Welcome greeting
    %th Return greeting
    %th Logo filename
    %th Headshot filename
    %th
    %th
    %th

  - @sponsor_details.each do |sponsor_detail|
    %tr
      %td= sponsor_detail.sponsor_id
      %td= sponsor_detail.company_name
      %td= sponsor_detail.contact_last_name
      %td= sponsor_detail.contact_first_name
      %td= sponsor_detail.phone_1
      %td= sponsor_detail.phone_2
      %td= sponsor_detail.website
      %td= sponsor_detail.email
      %td= sponsor_detail.tag_line_1
      %td= sponsor_detail.tag_line_2
      %td= sponsor_detail.welcome_greeting
      %td= sponsor_detail.return_greeting
      %td= sponsor_detail.logo_filename
      %td= sponsor_detail.headshot_filename
      %td= link_to 'Show', sponsor_detail
      %td= link_to 'Edit', edit_sponsor_detail_path(sponsor_detail)
      %td= link_to 'Destroy', sponsor_detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sponsor detail', new_sponsor_detail_path

app/views/*sponsor_details/new.html.haml
.row
  .small-6.columns
    %h4 Please enter your marketing details.
    %p This information will be used when generating your ads.

    = render 'form'

    = link_to 'Back', sponsor_details_path

app/views/*sponsor_details/show.html.haml
.row
  .small-8.columns
    %p#notice= notice
    %h4= t('views.sponsor_details.show.title')
    %table.table-settings

      %tr
        %td.small-4
          %b= t('company_name')
        %td
          = @sponsor_detail.company_name
      %tr
        %td
          %b=  t('contact_last_name')
        %td
          = @sponsor_detail.contact_last_name
      %tr
        %td
          %b=  t('contact_first_name')
        %td
          = @sponsor_detail.contact_first_name
      %tr
        %td
          %b=  t('primary_phone_number')
        %td
          = @sponsor_detail.phone_1
      %tr
        %td
          %b=  t('secondary_phone_number')
        %td
          = @sponsor_detail.phone_2
      %tr
        %td
          %b= t('website')
        %td
          = @sponsor_detail.website
      %tr
        %td
          %b= t('email')
        %td
          = @sponsor_detail.website
      %tr
        %td
          %b= t('tag_line_1')
        %td
          =@sponsor_detail.tag_line_1
      %tr
        %td
          %b= t('tag_line_2')
        %td
          = @sponsor_detail.tag_line_2
      %tr
        %td
          %b= t('welcome_greeting')
        %td
          = @sponsor_detail.welcome_greeting
      %tr
        %td
          %b= t('return_greeting')
        %td
          = @sponsor_detail.return_greeting
      %tr
        %td
          %b= t('logo_filename')
        %td
          = @sponsor_detail.logo_filename
      %tr
        %td
          %b= t('headshot_filename')
        %td
          = @sponsor_detail.headshot_filename


    = link_to t('views.nav.edit'), edit_sponsor_detail_path(@sponsor_detail), { id: 'link_show_edit'}
    -#\|
    -#= link_to t('views.nav.back'), sponsor_details_path, { class: 'link_show_back'}
.row
  .small-3.columns
    %p

app/views/layouts/menus/_main_navigation_menu.html.haml
-# navigation styled for Zurb Foundation 5
%nav.top-bar{'data-topbar' =>'', role:'navigation'}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      = link_to 'Menu', '#'
  %section.top-bar-section

    = render 'layouts/menus/main_navigation_menu_links'

app/views/layouts/menus/_main_navigation_menu_links.html.haml
-#add main navigation links to this file
%ul
  %li
    = link_to 'About', '#', {'data-reveal-id' => 'sponsor-modal'}

  - if (current_user.nil? && current_sponsor.nil? && current_staff.nil?)
    = render 'layouts/menus/sponsor_sign_in'
    = render 'layouts/menus/user_sign_in'
    = render 'layouts/menus/staff_sign_in'

    -# = render 'layouts/menus/user_sign_in'
    -# = render 'layouts/menus/staff_sign_in'


  - if sponsor_signed_in?
    = render 'layouts/menus/sponsor_sign_in'

  - if user_signed_in?
    = render 'layouts/menus/user_sign_in'

  - if staff_signed_in?
    = render 'layouts/menus/staff_sign_in'

  -# - if staff_signed_in?
  -#   = render 'layouts/menus/staff_sign_in'

app/views/layouts/menus/_sponsor_sign_in.html.haml
- if sponsor_signed_in?

  -#%ul.left
  -#  %li.has-dropdown
  -#    = link_to 'Home Owner', '#'
  -#    %ul.dropdown
  -#      %li
  -#        = link_to 'My Home', '#'
  -#      %li
  -#        = link_to 'Neighborhood', '#'
  -#  %li.has-dropdown
  -#    = link_to 'Dispute', '#'
  -#    %ul.dropdown
  -#      %li
  -#        = link_to 'Process', '#'
  -#      %li
  -#        = link_to 'Request CMA', '#'
  -#      %li
  -#        =  link_to 'Dispute', '#'

    -#- if @current_user_role != :user || @current_user_role == nil
    -#  %li.has-dropdown
    -#    = link_to 'Sponsorship Portal', portal_path
    -#    %ul.dropdown
    -#      -#%li
    -#      -#  = link_to 'Campaigns', campaigns_path
    -#      -#%li
    -#      -#  = link_to 'Advertisements', advertisements_path
    -#      -#- if @current_user_role == :b2c || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', csponsorships_path
    -#      -#- if @current_user_role == :b2b || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', bsponsorships_path
    -#      -#%li
    -#      -#  = link_to 'Sponsor Details', sponsor_detail_path(current_user)
    -#
    -#  = render 'layouts/menus/system'

  %ul.right
    %li.has-dropdown
      = link_to "#{current_sponsor.user_name}", '#'
      %ul.dropdown
        %li
          = link_to 'Sign out', destroy_sponsor_session_path, {method: :delete, :class => 'navbar-link'}
        %li
          = link_to 'Change password', edit_sponsor_registration_path
        %li
          = link_to 'Preferences', '#'

- else
  %ul.right
    %li
      = link_to 'Sponsor Sign in', new_sponsor_session_path, {:class => 'navbar-link'}



-#
-#- if user_signed_in?
-#
-#  %li
-#    = link_to 'Logout', destroy_user_session_path, {method: :delete, :class => 'navbar-link'}
-#
-#  %li.right
-#    = link_to "#{current_user.last_name}, #{current_user.first_name}", agent_path('0'), {:class => 'navbar-link'}
-#
-#  -#%li.logged-in-user
-#  -#  Logged in as
-#  -#  = current_user.email
-#- else
-#  -#%li
-#  -#  = link_to 'Sign up', new_user_registration_path, {:class => 'navbar-link'}
-#  %li
-#    = link_to 'Login', new_user_session_path, {:class => 'navbar-link'}

app/views/layouts/menus/_staff_sign_in.html.haml
- if staff_signed_in?

  -#%ul.left
  -#  %li.has-dropdown
  -#    = link_to 'Home Owner', '#'
  -#    %ul.dropdown
  -#      %li
  -#        = link_to 'My Home', '#'
  -#      %li
  -#        = link_to 'Neighborhood', '#'
  -#  %li.has-dropdown
  -#    = link_to 'Dispute', '#'
  -#    %ul.dropdown
  -#      %li
  -#        = link_to 'Process', '#'
  -#      %li
  -#        = link_to 'Request CMA', '#'
  -#      %li
  -#        =  link_to 'Dispute', '#'

    -#- if @current_user_role != :user || @current_user_role == nil
    -#  %li.has-dropdown
    -#    = link_to 'Sponsorship Portal', portal_path
    -#    %ul.dropdown
    -#      -#%li
    -#      -#  = link_to 'Campaigns', campaigns_path
    -#      -#%li
    -#      -#  = link_to 'Advertisements', advertisements_path
    -#      -#- if @current_user_role == :b2c || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', csponsorships_path
    -#      -#- if @current_user_role == :b2b || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', bsponsorships_path
    -#      -#%li
    -#      -#  = link_to 'Sponsor Details', sponsor_detail_path(current_user)
    -#
    -#  = render 'layouts/menus/system'

  %ul.right
    %li.has-dropdown
      = link_to "#{current_staff.user_name}", '#'
      %ul.dropdown
        %li
          = link_to 'Sign out', destroy_staff_session_path, {method: :delete, :class => 'navbar-link'}
        %li
          = link_to 'Change password', edit_staff_registration_path
        %li
          = link_to 'Preferences', '#'

- else
  %ul.right
    %li
      = link_to 'Staff Sign in', new_staff_session_path, {:class => 'navbar-link'}



-#
-#- if user_signed_in?
-#
-#  %li
-#    = link_to 'Logout', destroy_user_session_path, {method: :delete, :class => 'navbar-link'}
-#
-#  %li.right
-#    = link_to "#{current_user.last_name}, #{current_user.first_name}", agent_path('0'), {:class => 'navbar-link'}
-#
-#  -#%li.logged-in-user
-#  -#  Logged in as
-#  -#  = current_user.email
-#- else
-#  -#%li
-#  -#  = link_to 'Sign up', new_user_registration_path, {:class => 'navbar-link'}
-#  %li
-#    = link_to 'Login', new_user_session_path, {:class => 'navbar-link'}

app/views/layouts/menus/_system.html.haml
%li.has-dropdown
  = link_to 'Backend System', '#'
  %ul.dropdown
    -#%li
    -#  = link_to 'Campaigns', marketing_campaigns_path

    %li.has-dropdown
      = link_to 'Sponsorships', '#'
      %ul.dropdown
        -#%li
        -#  = link_to 'Sponsors', sponsors_path
        -#%li
        -#  = link_to 'B2B', bsponsorships_path
        -#%li
        -#  = link_to 'B2C', csponsorships_path

    %li.has-dropdown
      = link_to 'Ad Section', '#'
      %ul.dropdown
        -#%li
        -#  = link_to 'Rotations', ad_rotations_path
        -#-#%li
        -#-#  = link_to 'Advertisements', advertisements_path
        -#%li
        -#  = link_to 'Ads', ads_path
        -#%li
        -#  = link_to 'Ads System', ad_systems_path
        -#%li
        -#  = link_to 'Positions', ad_positions_path


    %li.has-dropdown
      = link_to 'Image Section', '#'
      %ul.dropdown
        -#%li
        -#  = link_to 'Images', images_path
        -#%li
        -#  = link_to 'Categories', image_categories_path
        -#%li
        -#  = link_to 'Presets', image_presets_path

    %li.has-dropdown
      = link_to 'Accounting', '#'
      %ul.dropdown
        -#%li
        -#  = link_to 'Payments', payments_path
        -#%li

    %li.has-dropdown
      = link_to t('menus.marketing.title'), '#'
      %ul.dropdown
        %li
          = link_to t('menus.marketing.campaigns'), marketing_campaigns_path
        %li
          = link_to t('menus.marketing.channels'), marketing_channels_path

    %li.has-dropdown
      = link_to 'Visitors', '#'
      %ul.dropdown
        %li
        -#  = link_to 'Client Machines', client_machines_path
        -#%li
        -#  = link_to 'Visits', visits_path

    %li.has-dropdown
      = link_to 'Reference', '#'
      %ul.dropdown
        -#%li
        -#  = link_to 'States', states_path
        -#%li
        -#  = link_to 'Listing Services', lservices_path
        -#%li
        -#  = link_to 'Industries', industries_path
        -#%li
        -#  = link_to 'Market Areas', market_areas_path
        -#%li
        -#  = link_to 'Counties', counties_path

app/views/layouts/menus/_user_sign_in.html.haml
- if user_signed_in?

  %ul.left
    %li.has-dropdown
      = link_to 'Home Owner', '#'
      %ul.dropdown
        %li
          = link_to 'My Home', '#'
        %li
          = link_to 'Neighborhood', '#'
    %li.has-dropdown
      = link_to 'Dispute', '#'
      %ul.dropdown
        %li
          = link_to 'Process', '#'
        %li
          = link_to 'Request CMA', '#'
        %li
          =  link_to 'Dispute', '#'

    -#- if @current_user_role != :user || @current_user_role == nil
    -#  %li.has-dropdown
    -#    = link_to 'Sponsorship Portal', portal_path
    -#    %ul.dropdown
    -#      -#%li
    -#      -#  = link_to 'Campaigns', campaigns_path
    -#      -#%li
    -#      -#  = link_to 'Advertisements', advertisements_path
    -#      -#- if @current_user_role == :b2c || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', csponsorships_path
    -#      -#- if @current_user_role == :b2b || @current_user_role == :support
    -#      -#  %li
    -#      -#    = link_to 'Sponsored', bsponsorships_path
    -#      -#%li
    -#      -#  = link_to 'Sponsor Details', sponsor_detail_path(current_user)
    -#
    -#  = render 'layouts/menus/system'

  %ul.right
    %li.has-dropdown
      = link_to "#{current_user.last_name}, #{current_user.first_name}", '#'
      %ul.dropdown
        %li
          = link_to 'Sign out', destroy_user_session_path, {method: :delete, :class => 'navbar-link'}
        %li
          = link_to 'Change password', edit_user_registration_path
        %li
          = link_to 'Preferences', '#'

- else
  %ul.right
    %li
      = link_to 'Sign in', new_user_session_path, {:class => 'navbar-link'}



-#
-#- if user_signed_in?
-#
-#  %li
-#    = link_to 'Logout', destroy_user_session_path, {method: :delete, :class => 'navbar-link'}
-#
-#  %li.right
-#    = link_to "#{current_user.last_name}, #{current_user.first_name}", agent_path('0'), {:class => 'navbar-link'}
-#
-#  -#%li.logged-in-user
-#  -#  Logged in as
-#  -#  = current_user.email
-#- else
-#  -#%li
-#  -#  = link_to 'Sign up', new_user_registration_path, {:class => 'navbar-link'}
-#  %li
-#    = link_to 'Login', new_user_session_path, {:class => 'navbar-link'}

app/views/sponsors-org/partials/_sponsored_table.html.haml
.row
  .small-6.columns
    This is where the list of sponsored clients go.

app/views/sponsors-org/partials/_support.html.haml
.row
  .small-6.columns
    This is what support sees.

.row
  .small-6.columns
    %p#notice= notice

    %p
      %b Industry:
      = @sponsor.d_industry_name
    %p
      %b Sponsorship type:
      = @sponsor.d_sponsor_type_name
    %p
      %b User:
      = @sponsor.d_user_full_name
    %p
      %b Business name:
      = @sponsor.business_name
    %p
      %b Phone:
      = @sponsor.phone
    %p
      %b Address 1:
      = @sponsor.address_1
    %p
      %b Address 2:
      = @sponsor.address_2
    %p
      %b City:
      = @sponsor.city
    %p
      %b State:
      = @sponsor.state_id
    %p
      %b Zipcode:
      = @sponsor.zipcode
    %p
      %b Website:
      = @sponsor.website
    %p
      %b Notes:
      = @sponsor.notes

    = link_to 'Edit', edit_sponsor_path(@sponsor), { id: 'link_show_edit'}
    \|
    = link_to 'Back', sponsors_path, { class: 'link_show_back'}

app/views/sponsors-org/reagent/_prospects.html.haml
.row
  .small-12.columns
    -#This is where the list of sponsored home owners go.
    -#= @prospects.inspect
    %h4 Participants
    %table.responsive
      %tr
        %th Email
        %th Name
        %th # visits
        %th Last visit
        %th Tax value
        %th Last CMA

      - @prospects.each do |prospect|
        %tr
          %td= prospect.user.email
          %td= "#{prospect.user.last_name}, #{prospect.user.first_name}"
          %td= prospect.user.sign_in_count
          %td= prospect.user.last_sign_in_at.strftime("%m/%d/%Y")
          %td= '$116,700.00'
          %td= '$124,600.00'

app/views/sponsors-org/responsor/_portal.html.haml
.row
  .small-10.columns
    .panel
      %b CPT ad to Title Co goes here.
.row
  .small-10.columns
    -#This is where the list of sponsored home owners go.
    -#= @prospects.inspect
    %h4.text-centered Sponsored Realtors
    %table
      %tr
        %th Team
        %th Home Owners
        %th Email
        %th Name
        %th # visits
        %th Last visit

      - @prospects.each do |prospect|
        %tr
          %td= prospect.sponsoree.business_name
          %td= prospect.sponsoree.sponsored
          %td= prospect.sponsoree.user.email
          %td= "#{prospect.sponsoree.user.last_name}, #{prospect.sponsoree.user.first_name}"
          %td= prospect.sponsoree.user.sign_in_count
          %td= prospect.sponsoree.user.last_sign_in_at.strftime("%m/%d/%Y")